task 07: filtering products
NastyaB3/surf-flutter-courses pull request #7
Opened 2023-06-30 07:58 UTC by NastyaB3

2023-07-05 08:18 UTC, mpkander requested changes

2023-07-05 08:18 UTC, mpkander commented on bin/07_task/07_task.dart
> +  List filteredList = rawProductItem
1. Не забывайте типизировать списки с помощью джейнериков: `List<RawProductItem>`
2. Не забывайте, что когда вы не указываете явно final/const/var, то по умолчанию используется var. В данном контексте переменная не меняется, то есть логичнее указать final, причём вполне себе хорошим решением будет указать просто `final filteredList = rawProductItem`

2023-07-05 08:18 UTC, mpkander commented on bin/07_task/07_task.dart
> +  filteredList.forEach((element) {
Ещё есть вариант использовать библиотеку collections. Эта библиотека не является частью стандрартного SDK, но является при этом стандартом индустрии. У нас в Surf она используется вообще на каждом проекте по умолчанию. В ней есть ряд методов, которые расширяют стандартное поведение коллекций. И это можно будет написать следующим образом: 

```dart
final groupedItemMap = filteredList
      .groupListsBy((element) => element.categoryName)
      .map((key, value) => MapEntry(
          key,
          value.groupListsBy((element) => element.subcategoryName).map((key, value) =>
              MapEntry(key, value.map((e) => e.name).toList()))));
```

2023-07-05 08:18 UTC, mpkander commented on bin/07_task/07_task.dart
> +  filteredList.forEach((element) {
Такие методы используются на практике гораздо чаще, потому что содержат гораздо меньше кода и имеют ожидаемую форму выполнения. При указании переменной таким образом Dart сам поймёт, что перед вами тип Map<String, Map<String, List<String>>>

2023-07-05 08:18 UTC, mpkander commented on bin/07_task/07_task.dart
> +  final Map productItemMap = {};
Тот же комментарий по части использования Map. Когда вы просто указываете Map, то он автоматически преобразуется в Map<dynamic>. Структура dynamic почти не используется в production-разработке в виду своей нестабильности и сложности чтения кода. Обычно её используют только для реализации простых и программ "на скорую руку".

Вас может смущать очень длинная и вложенная типизация для этой Map: Map<String, Map<String, List<String>>> 

В таком случае обычно мы используем typedef для структуризации и читаемости кода: 

```dart 
typedef GroupedByCategoryMap = Map<String, GroupedBySubcategory>;

typedef GroupedBySubcategory = Map<String, List<String>>;

```

2023-07-06 12:12 UTC, NastyaB3 commented on bin/07_task/07_task.dart
> +  final Map productItemMap = {};
да, меня смущала такая большая вложенность для типизации Map)

2023-07-06 12:13 UTC, merged